
[server]
debug=true
addr="192.168.0.105"
port=53

[mysql]
username = "root"
password = "root"
host = "127.0.0.1"
port = "3306"
database = "inimei"

[cache]
backend="memory"
expire = 600  # default expire time 10 minutes
maxcount = 100000

[resolv]
enable = false
resolv-file="/etc/resolv.conf"
timeout = 5  # 5 seconds
interval = 200 # 200 milliseconds

[hosts]
#If set false, will not query hosts file and redis hosts record
enable = true
host-file = "/etc/hosts"
redis-enable = false
redis-key = "godns:hosts"
ttl = 600
refresh-interval = 5 # 5 seconds

[redis]
host = "127.0.0.1"
port = 6379
db = 0
password =""