
[server]
debug=true
addr="192.168.0.105"
port=53
enableweb=true
enabledns=false

[web]
port=22280

[sqlite]
path="data.db"

[cache]
backend="memory"
expire = 600  # default expire time 10 minutes
maxcount = 100000

[resolv]
enable = false
resolv-file="/etc/resolv.conf"
timeout = 5  # 5 seconds
interval = 200 # 200 milliseconds

[hosts]
#If set false, will not query hosts file and redis hosts record
enable = true
host-file = "/etc/hosts"
ttl = 600
