
[server]
debug=false
addr=""
port=53
enableweb=true
enabledns=false
master=true

[slave]
master_host="http://ddns.ysong.site"
accesskey=""
secretKey=""
update_time=300  #seconds

[web]
port=22280
admin="yangsong@yangsong.site"
passwd="94f717fb79f5ea8b5dff0affbbdfdacd8335fbc2"  #sha1
#assets_image_host="https://ohgdnd9lh.qnssl.com"
assets_image_host=""

[session]
backend="memory" # redis
maxage=172800 # second

[sqlite]
path="data.db"

[cache]
backend="memory"
expire = 600  # default expire time 10 minutes
maxcount = 100000

[redis]
host = "127.0.0.1:6379"
passwd = ""

[resolv]
enable = true
resolv-file="ddns.d/resolv.conf"
timeout = 5  # 5 seconds
interval = 200 # 200 milliseconds

[hosts]
#If set false, will not query hosts file and redis hosts record
enable = false
host-file = "ddns.d//hosts"
ttl = 600

[download]
enable = true
dest = "/home/yangsongfwd/download"